<?php
/** @var \Magento\Framework\View\Element\Template $block */

$viewModel = $block->getViewModel();
$categories = [4,6];
$products = $viewModel->getProducts($categories);

?>
<h2><?= __('Список продуктов из заданого списка категорий '); ?></h2>
<table style="border: 1px solid #ccc; ">
    <tr style="background-color: #ccc">
        <td>
            <?=  __('Id product: ') ?>
        </td>
        <td>склади</td>
        <td>Имя продукта</td>
        <td>Цена</td>
        <td>Sku</td>
        <td>Изображение</td>
    </tr>
    <?php foreach ($products as $item) : ?>

        <?php  $prodInfo = $viewModel->getProductById((int)$item->getIdProd());
        $warehouses = $viewModel->getWarehouses((int)$item->getIdProd());
        ?>
        <tr style="border: 1px solid #ccc; " >
            <td><?= $item->getIdProd() ?></td>
            <td><ul><?php foreach ($warehouses as $warehouse) : ?>
              <li><<?= $warehouse->getNameWar() ?></li>
              <?php endforeach; ?>
              </ul>
          </td>

          <td><?= $prodInfo->getName() ?></td>
          <td><?= $prodInfo->getPrice() ?></td>
          <td><?= $prodInfo->getSku() ?></td>
            <td><img width="100px" height="100px" src="<?= $block->getUrl(). 'media/catalog/product'.$prodInfo->getImage() ?>" alt="<?= $prodInfo->getName() ?>" /></td>
        </tr>
    <?php endforeach; ?>
</table>
